=== Andrefish4/inf24tig16/data/utilizadores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="utilizadores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="utilizador" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="primeiroNome" type="xs:string"/>
              <xs:element name="ultimoNome" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="password" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Andrefish4/inf24tig16/data/utilizadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<utilizadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="utilizadores.xsd">
  <utilizador>
    <primeiroNome>Ricardo</primeiroNome>
    <ultimoNome>Dias</ultimoNome>
    <email>ricardo@edu.pt</email>
    <password>1234</password>
  </utilizador>
  
  <utilizador>
    <primeiroNome>João</primeiroNome>
    <ultimoNome>Oliveira</ultimoNome>
    <email>A046461@umaia.pt</email>
    <password>1234</password>
  </utilizador>

  <utilizador>
    <primeiroNome>André</primeiroNome>
    <ultimoNome>Pereira</ultimoNome>
    <email>A046761@umaia.pt</email>
    <password>1234</password>
  </utilizador>
  
</utilizadores>
